PROCESSOR_HOME ?= ../../..

UART_SOURCE   := $(PROCESSOR_HOME)/sw/uart_lib/c_lang/uart_lib.c
SRC 		  += $(UART_SOURCE)

C_INC += -I $(PROCESSOR_HOME)/sw/uart_lib/common/ -I $(PROCESSOR_HOME)/sw/uart_lib/c_lang/

include $(PROCESSOR_HOME)/sw/common/common.mk