PROCESSOR_HOME ?= ../../..

UART_SOURCE   := $(PROCESSOR_HOME)/sw/uart_lib/assembly/uart_lib.S
SRC 		  += $(UART_SOURCE)

ASM_INC += -I $(PROCESSOR_HOME)/sw/uart_lib/common/

include $(PROCESSOR_HOME)/sw/common/common.mk

